name: Pipeline
on:
  push:
permissions:
  contents: write
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  release:
    name: Release
    needs: ci
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ github.ref_name }}
    secrets: inherit
